//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Exams = new HashSet<Exam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public Nullable<float> Duration { get; set; }
    
        public virtual ICollection<Exam> Exams { get; set; }
    }
}
