//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuesCategory
    {
        public QuesCategory()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExamQuestion { get; set; }
        public Nullable<int> TotalQuestion { get; set; }
        public int AdminId { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Admin Admin { get; set; }
    }
}
