//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Question
    {
        public int Id { get; set; }

        [DisplayName("Question")]
        public string Text { get; set; }

        [DisplayName("Option-A")]
        public string OPA { get; set; }

        [DisplayName("Option-B")]
        public string OPB { get; set; }

        [DisplayName("Option-C")]
        public string OPC { get; set; }

        [DisplayName("Option-D")]
        public string OPD { get; set; }

        [DisplayName("Correct Option")]
        public string COP { get; set; }
        public int QuesCategoryId { get; set; }
    
        public virtual QuesCategory QuesCategory { get; set; }
    }
}
