//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExam.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public Student()
        {
            this.SetExams = new HashSet<Report>();
        }

        public int Id { get; set; }

        [DisplayName("First Name")]
        [Required(ErrorMessage = "The First Name is required")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Contact Number")]
        [Required(ErrorMessage = "The Contact Number is required")]
        public int PhoneNumber { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [DisplayName("College Name")]
        [Required(ErrorMessage = "The College Name is required")]
        public string CollegeName { get; set; }

        [DisplayName("College Roll No")]
        [Required(ErrorMessage = "The Roll Number is required")]
        public string CollegeRollNo { get; set; }

        [Required(ErrorMessage = "The Branch Name is required")]
        public string Branch { get; set; }

        public virtual ICollection<Report> SetExams { get; set; }
    }
}
